spring.application.name=products

# MongoDB configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=productDB
spring.data.mongodb.auto-index-creation=true

# Spring Boot application configuration
server.address=0.0.0.0
server.port=8080

# Logging for debugging (optional)
logging.level.org.springframework.data.mongodb.core=DEBUG